#!/usr/bin/env python3
"""Regenerate the ending table in `web/languages/it/regular.py` from the source.

Same argument as `regular_endings.py` makes for Portuguese: rather than type the
endings from memory, derive them. Fetch Reverso's own model verbs, subtract the
stem, and print what is left — so the table is measured against exactly the
source the verbs it judges will come from.

Italian needs four columns, not three. `-ire` splits into two regular patterns:
the plain one (`partire` -> `parto`) and the `-isc-` infixing one (`capire` ->
`capisco`). Both are entirely regular; which one a verb takes is simply not
predictable from the infinitive, so `regular.py` accepts either.

Usage (from src/python/web, in a container):
    python tools/italian_endings.py            # print the table
    python tools/italian_endings.py --check    # compare with what's committed
    python tools/italian_endings.py --offline  # use the saved test fixtures

Exits non-zero under --check if the source has moved, so it can be a CI step.
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from web.languages.it import catalogue, reverso  # noqa: E402
from web.languages.it.adapter import BLOCK_TENSES  # noqa: E402
from web.languages.it.regular import ENDINGS, PATTERNS  # noqa: E402

FIXTURES = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "reverso"

# One model verb per regular pattern, in PATTERNS order, with its stem.
MODELS = [("parlare", "parl"), ("credere", "cred"), ("partire", "part"), ("capire", "cap")]

PAUSE = 1.5


async def _raw(verb: str, offline: bool) -> reverso.RawParadigm:
    if offline:
        page = (FIXTURES / f"verb-{verb}.html").read_text(encoding="utf-8")
        return reverso.parse_paradigm(page, verb, catalogue.person_key)
    async with reverso.ReversoClient() as client:
        return await client.paradigm(verb, catalogue.person_key)


async def build(offline: bool) -> dict[tuple[str, str], tuple[tuple[str, ...], ...]]:
    """``(tense, person) -> the endings each pattern allows``, by subtraction.

    A pattern's entry is a tuple because a cell can have more than one regular
    ending: the ``-ere`` passato remoto really does take both ``credetti`` and
    ``credei``, and treating that as an irregularity would call every regular
    ``-ere`` verb irregular.
    """
    columns: list[dict[tuple[str, str], tuple[str, ...]]] = []
    for index, (verb, stem) in enumerate(MODELS):
        raw = await _raw(verb, offline)
        column: dict[tuple[str, str], tuple[str, ...]] = {}
        for (title, person), forms in raw.cells.items():
            tense = BLOCK_TENSES.get(title)
            if tense is None:
                continue  # a block this drill does not use
            person = person or catalogue.INVARIABLE_PERSON
            odd = [f for f in forms if not f.startswith(stem)]
            if odd:
                print(f"  ! {verb} {tense}.{person}: {odd} do not start with {stem!r}",
                      file=sys.stderr)
            endings = tuple(f[len(stem):] for f in forms if f.startswith(stem))
            if endings:
                column[(tense, person)] = endings
        columns.append(column)
        if not offline and index < len(MODELS) - 1:
            await asyncio.sleep(PAUSE)

    keys = sorted(set().union(*(c.keys() for c in columns)))
    table: dict[tuple[str, str], tuple[tuple[str, ...], ...]] = {}
    for key in keys:
        missing = [MODELS[i][0] for i, c in enumerate(columns) if key not in c]
        if missing:
            print(f"  ! {key} absent for {', '.join(missing)}", file=sys.stderr)
            continue
        table[key] = tuple(c[key] for c in columns)
    return table


def render(table: dict[tuple[str, str], tuple[str, ...]]) -> str:
    lines = [f"# Generated by tools/italian_endings.py. Patterns: {', '.join(PATTERNS)}.",
             "# Each entry is one tuple of accepted endings per pattern, in that order.",
             "ENDINGS: dict[tuple[str, str], tuple[tuple[str, ...], ...]] = {"]
    for (tense, person), per_pattern in sorted(table.items()):
        rendered = ", ".join(
            "(" + ", ".join(f'"{e}"' for e in endings) + ("," if len(endings) == 1 else "") + ")"
            for endings in per_pattern
        )
        lines.append(f'    ("{tense}", "{person}"): ({rendered}),')
    lines.append("}")
    return "\n".join(lines)


async def main(argv: list[str]) -> int:
    offline = "--offline" in argv
    table = await build(offline)

    if "--check" in argv:
        if table == ENDINGS:
            print(f"ok — {len(table)} endings match web/languages/it/regular.py")
            return 0
        for key in sorted(set(table) | set(ENDINGS)):
            if table.get(key) != ENDINGS.get(key):
                print(f"  {key}: source={table.get(key)} committed={ENDINGS.get(key)}")
        print("MISMATCH — regenerate with tools/italian_endings.py")
        return 1

    print(render(table))
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main(sys.argv[1:])))
