#!/usr/bin/env python3
"""Regenerate the ending table in `web/languages/es/regular.py` from the source.

Same argument as `regular_endings.py` makes for Portuguese and
`italian_endings.py` for Italian: rather than type the endings from memory,
derive them. Fetch Reverso's own model verbs, subtract the stem, and print what
is left — so the table is measured against exactly the source the verbs it
judges will come from.

Three columns, one per conjugation. Only the simple tenses appear: a compound
tense is *haber* plus the participle, so its forms do not begin with the stem
and there is nothing to subtract. `regular.py` excludes them for the same
reason, and says why.

Unlike the Italian tool this reads the adapter's own `to_paradigm` rather than
the raw blocks, because Spanish maps two Reverso blocks onto one cell — the
imperfect subjunctive's `hablara` and `hablase` — and reading the blocks
directly would keep only whichever came last.

Usage (from src/python/web, in a container):
    python tools/spanish_endings.py            # print the table
    python tools/spanish_endings.py --check    # compare with what's committed
    python tools/spanish_endings.py --offline  # use the saved test fixtures

Exits non-zero under --check if the source has moved, so it can be a CI step.
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from web.languages import reverso  # noqa: E402
from web.languages.es import catalogue  # noqa: E402
from web.languages.es.adapter import SITE, to_paradigm  # noqa: E402
from web.languages.es.regular import ENDINGS, PATTERNS  # noqa: E402

FIXTURES = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "reverso"

# One model verb per regular pattern, in PATTERNS order, with its stem.
MODELS = [("hablar", "habl"), ("comer", "com"), ("vivir", "viv")]

PAUSE = 1.5


async def _cells(verb: str, offline: bool):
    if offline:
        page = (FIXTURES / f"es-verb-{verb}.html").read_text(encoding="utf-8")
        raw = reverso.parse_paradigm(page, verb, catalogue.person_key, SITE)
    else:
        async with reverso.ReversoClient(SITE) as client:
            raw = await client.paradigm(verb, catalogue.person_key)
    return to_paradigm(raw).cells


async def build(offline: bool) -> dict[tuple[str, str], tuple[tuple[str, ...], ...]]:
    """``(tense, person) -> the endings each pattern allows``, by subtraction.

    A pattern's entry is a tuple because a cell can have more than one regular
    ending: the imperfect subjunctive really does take both ``hablara`` and
    ``hablase``, and treating that as an irregularity would call every Spanish
    verb irregular.

    A cell whose forms do not start with the stem is a compound tense and is
    dropped without comment; anything else that fails to subtract is reported.
    """
    columns: list[dict[tuple[str, str], tuple[str, ...]]] = []
    for index, (verb, stem) in enumerate(MODELS):
        column: dict[tuple[str, str], tuple[str, ...]] = {}
        for key, cell in (await _cells(verb, offline)).items():
            endings = tuple(f[len(stem):] for f in cell.forms if f.startswith(stem))
            if len(endings) == len(cell.forms):
                column[key] = endings
            elif endings:
                print(f"  ! {verb} {key}: only some forms start with {stem!r}: "
                      f"{cell.forms}", file=sys.stderr)
        columns.append(column)
        if not offline and index < len(MODELS) - 1:
            await asyncio.sleep(PAUSE)

    keys = sorted(set().union(*(c.keys() for c in columns)))
    table: dict[tuple[str, str], tuple[tuple[str, ...], ...]] = {}
    for key in keys:
        missing = [MODELS[i][0] for i, c in enumerate(columns) if key not in c]
        if missing:
            print(f"  ! {key} absent for {', '.join(missing)}", file=sys.stderr)
            continue
        table[key] = tuple(c[key] for c in columns)
    return table


def render(table: dict[tuple[str, str], tuple[str, ...]]) -> str:
    lines = [f"# Generated by tools/spanish_endings.py. Patterns: {', '.join(PATTERNS)}.",
             "# Each entry is one tuple of accepted endings per pattern, in that order.",
             "ENDINGS: dict[tuple[str, str], tuple[tuple[str, ...], ...]] = {"]
    for (tense, person), per_pattern in sorted(table.items()):
        rendered = ", ".join(
            "(" + ", ".join(f'"{e}"' for e in endings) + ("," if len(endings) == 1 else "") + ")"
            for endings in per_pattern
        )
        lines.append(f'    ("{tense}", "{person}"): ({rendered}),')
    lines.append("}")
    return "\n".join(lines)


async def main(argv: list[str]) -> int:
    offline = "--offline" in argv
    table = await build(offline)

    if "--check" in argv:
        if table == ENDINGS:
            print(f"ok — {len(table)} endings match web/languages/es/regular.py")
            return 0
        for key in sorted(set(table) | set(ENDINGS)):
            if table.get(key) != ENDINGS.get(key):
                print(f"  {key}: source={table.get(key)} committed={ENDINGS.get(key)}")
        print("MISMATCH — regenerate with tools/spanish_endings.py")
        return 1

    print(render(table))
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main(sys.argv[1:])))
