"""How predictable is this Italian verb, given its infinitive?

Adding a verb stops to confirm, and this is what that confirmation reports —
the same three verdicts as the Portuguese check, reached the same way, but over
Italian's own patterns.

Italian has **four** regular patterns where Portuguese has three. ``-ire``
splits in two: the plain conjugation (``partire`` → ``parto``) and the one that
infixes ``-isc-`` in the singular and third plural (``capire`` → ``capisco``,
``capisca``). Both are completely regular; which a verb takes simply is not
recoverable from the infinitive, so an ``-ire`` verb is checked against both and
counts as regular if it matches either.

The spelling changes are Italian's own and go the opposite way from Portuguese's.
An ``-are`` stem is written against a back vowel, so a front-vowel ending
disturbs it: ``cercare`` → ``cerchi`` keeps the /k/, ``pagare`` → ``paghi``
keeps the /g/, and ``cominciare`` → ``cominci`` drops an ``i`` that would
otherwise double. ``-ere`` and ``-ire`` need none: Italian simply lets ``leggo``
and ``leggi`` differ in sound at the same spelling.

The table is not typed from memory. ``tools/italian_endings.py`` regenerates it
by fetching Reverso's own ``parlare`` / ``credere`` / ``partire`` / ``capire``
and subtracting the stem, so the endings come from the same source as the verbs
they are compared against.

Errors here are one-sided by construction, as in Portuguese: a missing spelling
rule makes a regular verb look irregular, understating how predictable it is,
while the reverse would need the table to reproduce an irregular paradigm
exactly, which it cannot.
"""

from __future__ import annotations

from dataclasses import dataclass

from ..base import Paradigm

# What the check can conclude about a verb.
REGULAR = "regular"
REGULAR_WITH_SPELLING = "regular_with_spelling"
IRREGULAR = "irregular"

# The four regular patterns, in the order the ending table's columns run.
PATTERNS = ("are", "ere", "ire", "ire-isc")

# How each pattern is named to the user.
PATTERN_NAMES = {
    "are": "-are",
    "ere": "-ere",
    "ire": "-ire",
    "ire-isc": "-ire (with the -isc- infix)",
}

# Generated by tools/italian_endings.py. Patterns: are, ere, ire, ire-isc.
# Each entry is one tuple of accepted endings per pattern, in that order.
ENDINGS: dict[tuple[str, str], tuple[tuple[str, ...], ...]] = {
    ("condizionale_presente", "io"): (("erei",), ("erei",), ("irei",), ("irei",)),
    ("condizionale_presente", "loro"): (("erebbero",), ("erebbero",), ("irebbero",), ("irebbero",)),
    ("condizionale_presente", "lui"): (("erebbe",), ("erebbe",), ("irebbe",), ("irebbe",)),
    ("condizionale_presente", "noi"): (("eremmo",), ("eremmo",), ("iremmo",), ("iremmo",)),
    ("condizionale_presente", "tu"): (("eresti",), ("eresti",), ("iresti",), ("iresti",)),
    ("condizionale_presente", "voi"): (("ereste",), ("ereste",), ("ireste",), ("ireste",)),
    ("congiuntivo_imperfetto", "io"): (("assi",), ("essi",), ("issi",), ("issi",)),
    ("congiuntivo_imperfetto", "loro"): (("assero",), ("essero",), ("issero",), ("issero",)),
    ("congiuntivo_imperfetto", "lui"): (("asse",), ("esse",), ("isse",), ("isse",)),
    ("congiuntivo_imperfetto", "noi"): (("assimo",), ("essimo",), ("issimo",), ("issimo",)),
    ("congiuntivo_imperfetto", "tu"): (("assi",), ("essi",), ("issi",), ("issi",)),
    ("congiuntivo_imperfetto", "voi"): (("aste",), ("este",), ("iste",), ("iste",)),
    ("congiuntivo_presente", "io"): (("i",), ("a",), ("a",), ("isca",)),
    ("congiuntivo_presente", "loro"): (("ino",), ("ano",), ("ano",), ("iscano",)),
    ("congiuntivo_presente", "lui"): (("i",), ("a",), ("a",), ("isca",)),
    ("congiuntivo_presente", "noi"): (("iamo",), ("iamo",), ("iamo",), ("iamo",)),
    ("congiuntivo_presente", "tu"): (("i",), ("a",), ("a",), ("isca",)),
    ("congiuntivo_presente", "voi"): (("iate",), ("iate",), ("iate",), ("iate",)),
    ("futuro_semplice", "io"): (("erò",), ("erò",), ("irò",), ("irò",)),
    ("futuro_semplice", "loro"): (("eranno",), ("eranno",), ("iranno",), ("iranno",)),
    ("futuro_semplice", "lui"): (("erà",), ("erà",), ("irà",), ("irà",)),
    ("futuro_semplice", "noi"): (("eremo",), ("eremo",), ("iremo",), ("iremo",)),
    ("futuro_semplice", "tu"): (("erai",), ("erai",), ("irai",), ("irai",)),
    ("futuro_semplice", "voi"): (("erete",), ("erete",), ("irete",), ("irete",)),
    ("gerundio", "inv"): (("ando",), ("endo",), ("endo",), ("endo",)),
    ("imperativo", "loro"): (("ino",), ("ano",), ("ano",), ("iscano",)),
    ("imperativo", "lui"): (("i",), ("a",), ("a",), ("isca",)),
    ("imperativo", "noi"): (("iamo",), ("iamo",), ("iamo",), ("iamo",)),
    ("imperativo", "tu"): (("a",), ("i",), ("i",), ("isci",)),
    ("imperativo", "voi"): (("ate",), ("ete",), ("ite",), ("ite",)),
    ("imperfetto", "io"): (("avo",), ("evo",), ("ivo",), ("ivo",)),
    ("imperfetto", "loro"): (("avano",), ("evano",), ("ivano",), ("ivano",)),
    ("imperfetto", "lui"): (("ava",), ("eva",), ("iva",), ("iva",)),
    ("imperfetto", "noi"): (("avamo",), ("evamo",), ("ivamo",), ("ivamo",)),
    ("imperfetto", "tu"): (("avi",), ("evi",), ("ivi",), ("ivi",)),
    ("imperfetto", "voi"): (("avate",), ("evate",), ("ivate",), ("ivate",)),
    ("participio_passato", "inv"): (("ato",), ("uto",), ("ito",), ("ito",)),
    ("passato_remoto", "io"): (("ai",), ("etti", "ei"), ("ii",), ("ii",)),
    ("passato_remoto", "loro"): (("arono",), ("ettero", "erono"), ("irono",), ("irono",)),
    ("passato_remoto", "lui"): (("ò",), ("ette", "é"), ("ì",), ("ì",)),
    ("passato_remoto", "noi"): (("ammo",), ("emmo",), ("immo",), ("immo",)),
    ("passato_remoto", "tu"): (("asti",), ("esti",), ("isti",), ("isti",)),
    ("passato_remoto", "voi"): (("aste",), ("este",), ("iste",), ("iste",)),
    ("presente", "io"): (("o",), ("o",), ("o",), ("isco",)),
    ("presente", "loro"): (("ano",), ("ono",), ("ono",), ("iscono",)),
    ("presente", "lui"): (("a",), ("e",), ("e",), ("isce",)),
    ("presente", "noi"): (("iamo",), ("iamo",), ("iamo",), ("iamo",)),
    ("presente", "tu"): (("i",), ("i",), ("i",), ("isci",)),
    ("presente", "voi"): (("ate",), ("ete",), ("ite",), ("ite",)),
}

# Respellings that keep an -are stem's final consonant sounding the same when
# the ending starts with a front vowel. Tried in order, first match wins — so
# "sci" is listed before "ci", and "ci"/"gi" before bare "c"/"g".
_ARE_RESPELL = (
    ("sci", "sc"),   # lasciare -> lasci, lascerò
    ("ci", "c"),     # cominciare -> cominci, comincerò
    ("gi", "g"),     # mangiare -> mangi, mangerò
    ("c", "ch"),     # cercare -> cerchi, cercherò
    ("g", "gh"),     # pagare -> paghi, pagherò
)
_FRONT_VOWELS = frozenset("ei")


def _infinitive_ending(infinitive: str) -> str | None:
    """``are``/``ere``/``ire``, or ``None`` outside the three conjugations."""
    for ending in ("are", "ere", "ire"):
        if infinitive.endswith(ending) and len(infinitive) > len(ending):
            return ending
    return None


def patterns_for(infinitive: str) -> list[str]:
    """Which regular patterns this infinitive could follow.

    One for ``-are`` and ``-ere``; two for ``-ire``, which gives no clue
    whether the verb infixes ``-isc-``.
    """
    ending = _infinitive_ending(infinitive)
    if ending is None:
        return []
    return ["ire", "ire-isc"] if ending == "ire" else [ending]


def _join(stem: str, ending: str, pattern: str) -> str:
    """Stem + ending, respelling an ``-are`` stem before a front vowel."""
    if pattern != "are" or not ending or ending[0] not in _FRONT_VOWELS:
        return stem + ending
    for old, new in _ARE_RESPELL:
        if stem.endswith(old):
            return stem[: len(stem) - len(old)] + new + ending
    return stem + ending


def regular_forms(
    infinitive: str, pattern: str
) -> dict[tuple[str, str], tuple[str, ...]] | None:
    """Every cell a verb of this shape would have under ``pattern``.

    Each cell maps to *all* the forms the pattern accepts there, which is more
    than one where the pattern itself offers a choice — the ``-ere`` passato
    remoto takes both ``credetti`` and ``credei``.

    ``None`` if the infinitive is outside the three conjugations, or the
    pattern does not apply to it.
    """
    if pattern not in patterns_for(infinitive):
        return None
    index = PATTERNS.index(pattern)
    stem = infinitive[:-3]
    return {
        key: tuple(_join(stem, ending, pattern) for ending in endings[index])
        for key, endings in ENDINGS.items()
    }


# Cells to quote a spelling change from, most recognisable first.
_EXAMPLE_CELLS = (
    ("presente", "tu"),
    ("congiuntivo_presente", "io"),
    ("futuro_semplice", "io"),
)


@dataclass(frozen=True)
class Spelling:
    """A stem respelling that runs through a whole paradigm predictably."""

    old: str
    new: str
    before: str  # the vowels that trigger it, e.g. "e/i"
    examples: tuple[str, ...]

    def describe(self) -> str:
        return f"{self.old} → {self.new} before {self.before} ({', '.join(self.examples)})"


def spelling_change(infinitive: str) -> Spelling | None:
    """The one respelling this verb's stem needs, if any."""
    if "are" not in patterns_for(infinitive):
        return None
    index = PATTERNS.index("are")
    stem = infinitive[:-3]

    change = next(((o, n) for o, n in _ARE_RESPELL if stem.endswith(o)), None)
    if change is None:
        return None

    vowels = sorted(
        {
            ending[0]
            for e in ENDINGS.values()
            for ending in e[index]
            if ending and ending[0] in _FRONT_VOWELS
        }
    )
    # Deduplicated: several cells share an ending, so quoting them all would
    # print "cerchi, cerchi" instead of "cerchi, cercherò".
    examples: list[str] = []
    for key in _EXAMPLE_CELLS:
        if key not in ENDINGS:
            continue
        ending = ENDINGS[key][index][0]
        form = _join(stem, ending, "are")
        if form != stem + ending and form not in examples:
            examples.append(form)
    return Spelling(*change, before="/".join(vowels), examples=tuple(examples[:2]))


@dataclass(frozen=True)
class Classification:
    kind: str
    pattern: str | None = None
    spelling: Spelling | None = None

    @property
    def is_regular(self) -> bool:
        return self.kind != IRREGULAR

    def describe(self) -> str:
        """The verdict as a clause to follow the infinitive."""
        if self.kind == IRREGULAR:
            return "is an irregular verb."
        named = PATTERN_NAMES.get(self.pattern, self.pattern)
        if self.kind == REGULAR:
            return f"is a regular {named} verb."
        return (
            f"is a regular {named} verb, apart from a spelling change: "
            f"{self.spelling.describe()}."
        )


def classify(paradigm: Paradigm) -> Classification:
    """Predictable, predictable-but-respelt, or worth drilling.

    Deliberately strict: the cells must match one pattern exactly, so a verb
    carrying an extra accepted form anywhere is irregular. That form is the
    whole reason to drill it.
    """
    for pattern in patterns_for(paradigm.infinitive):
        expected = regular_forms(paradigm.infinitive, pattern)
        if expected is None or set(paradigm.cells) != set(expected):
            continue
        # Compared as sets: which of several equally regular forms the source
        # happens to list first is not a signal about the verb.
        if not all(
            set(cell.forms) == set(expected[key]) for key, cell in paradigm.cells.items()
        ):
            continue
        change = spelling_change(paradigm.infinitive)
        return (
            Classification(REGULAR_WITH_SPELLING, pattern, change)
            if change
            else Classification(REGULAR, pattern)
        )
    return Classification(IRREGULAR)


def is_regular(paradigm: Paradigm) -> bool:
    """True when the paradigm holds nothing the ending table doesn't predict."""
    return classify(paradigm).is_regular
