"""How predictable is this Spanish verb, given its infinitive?

Adding a verb stops to confirm, and this is what that confirmation reports —
the same three verdicts as the Portuguese and Italian checks, reached the same
way, over Spanish's own patterns.

Three patterns, one per conjugation: ``-ar``, ``-er``, ``-ir``. Unlike Italian's
``-ire``, neither Spanish ending splits, so the infinitive names the pattern
outright.

**Only the simple tenses are in the table.** A compound tense is *haber* plus
the past participle, and *haber* is the same for every verb in the language, so
a verb whose participle is regular has six regular compound tenses for free.
Checking them would mean writing ``he ``, ``has ``, ``había `` into an ending
table that exists to describe stems, and would say nothing the participle row
has not already said.

**The spelling changes run both ways**, which Portuguese's and Italian's do not.
A stem's last consonant has to keep its sound when the ending's first vowel
changes side:

- an ``-ar`` stem is written against a back vowel, so a *front* vowel disturbs
  it — ``buscar`` → ``busqué``, ``llegar`` → ``llegué``, ``cruzar`` → ``crucé``,
  ``averiguar`` → ``averigüé``
- an ``-er``/``-ir`` stem is written against a front vowel, so a *back* vowel
  disturbs it — ``vencer`` → ``venzo``, ``coger`` → ``cojo``, ``distinguir`` →
  ``distingo``, ``delinquir`` → ``delinco``

**Two gaps worth knowing about.** The first is reflexives. ``levantarse`` does
not end in ``-ar``, ``-er`` or ``-ir``, so no pattern applies and it is
irregular by default — and even with the ``-se`` stripped its drilled answers
carry a clitic (``me levanto``) that no ending table predicts. Every reflexive
verb therefore reports as irregular, including entirely regular ones.

The second is stem changes — ``pensar`` → ``pienso``, ``poder`` → ``puedo``,
``pedir`` → ``pido``. Which vowel changes, and whether one changes at all, is
not recoverable from the infinitive (``pensar`` changes, ``pasar`` does not), so
these classify as irregular too.

Both are the same one-sided error Portuguese and Italian already document: a
missing rule understates how predictable a verb is, never the reverse, since
overstating it would need the table to reproduce an irregular paradigm exactly.
But it bites harder here, because reflexives and stem-changers are ordinary
Spanish 1 vocabulary rather than a handful of exceptions. Expect ``describe()``
to say "irregular" for a large minority of perfectly ordinary verbs.

The table is not typed from memory. ``tools/spanish_endings.py`` regenerates it
by fetching Reverso's own ``hablar`` / ``comer`` / ``vivir`` and subtracting the
stem, so the endings come from the same source as the verbs they are compared
against.
"""

from __future__ import annotations

from dataclasses import dataclass

from ..base import Paradigm

# What the check can conclude about a verb.
REGULAR = "regular"
REGULAR_WITH_SPELLING = "regular_with_spelling"
IRREGULAR = "irregular"

# The three regular patterns, in the order the ending table's columns run.
PATTERNS = ("ar", "er", "ir")

# How each pattern is named to the user.
PATTERN_NAMES = {"ar": "-ar", "er": "-er", "ir": "-ir"}

# Generated by tools/spanish_endings.py. Patterns: ar, er, ir.
# Each entry is one tuple of accepted endings per pattern, in that order.
ENDINGS: dict[tuple[str, str], tuple[tuple[str, ...], ...]] = {
    ("condicional", "el"): (("aría",), ("ería",), ("iría",)),
    ("condicional", "ellos"): (("arían",), ("erían",), ("irían",)),
    ("condicional", "nos"): (("aríamos",), ("eríamos",), ("iríamos",)),
    ("condicional", "tu"): (("arías",), ("erías",), ("irías",)),
    ("condicional", "vos"): (("aríais",), ("eríais",), ("iríais",)),
    ("condicional", "yo"): (("aría",), ("ería",), ("iría",)),
    ("futuro", "el"): (("ará",), ("erá",), ("irá",)),
    ("futuro", "ellos"): (("arán",), ("erán",), ("irán",)),
    ("futuro", "nos"): (("aremos",), ("eremos",), ("iremos",)),
    ("futuro", "tu"): (("arás",), ("erás",), ("irás",)),
    ("futuro", "vos"): (("aréis",), ("eréis",), ("iréis",)),
    ("futuro", "yo"): (("aré",), ("eré",), ("iré",)),
    ("gerundio", "inv"): (("ando",), ("iendo",), ("iendo",)),
    ("imperativo", "el"): (("e",), ("a",), ("a",)),
    ("imperativo", "ellos"): (("en",), ("an",), ("an",)),
    ("imperativo", "nos"): (("emos",), ("amos",), ("amos",)),
    ("imperativo", "tu"): (("a",), ("e",), ("e",)),
    ("imperativo", "vos"): (("ad",), ("ed",), ("id",)),
    ("imperfecto", "el"): (("aba",), ("ía",), ("ía",)),
    ("imperfecto", "ellos"): (("aban",), ("ían",), ("ían",)),
    ("imperfecto", "nos"): (("ábamos",), ("íamos",), ("íamos",)),
    ("imperfecto", "tu"): (("abas",), ("ías",), ("ías",)),
    ("imperfecto", "vos"): (("abais",), ("íais",), ("íais",)),
    ("imperfecto", "yo"): (("aba",), ("ía",), ("ía",)),
    ("participio", "inv"): (("ado",), ("ido",), ("ido",)),
    ("presente", "el"): (("a",), ("e",), ("e",)),
    ("presente", "ellos"): (("an",), ("en",), ("en",)),
    ("presente", "nos"): (("amos",), ("emos",), ("imos",)),
    ("presente", "tu"): (("as",), ("es",), ("es",)),
    ("presente", "vos"): (("áis",), ("éis",), ("ís",)),
    ("presente", "yo"): (("o",), ("o",), ("o",)),
    ("preterito", "el"): (("ó",), ("ió",), ("ió",)),
    ("preterito", "ellos"): (("aron",), ("ieron",), ("ieron",)),
    ("preterito", "nos"): (("amos",), ("imos",), ("imos",)),
    ("preterito", "tu"): (("aste",), ("iste",), ("iste",)),
    ("preterito", "vos"): (("asteis",), ("isteis",), ("isteis",)),
    ("preterito", "yo"): (("é",), ("í",), ("í",)),
    ("subjuntivo_imperfecto", "el"): (("ara", "ase"), ("iera", "iese"), ("iera", "iese")),
    ("subjuntivo_imperfecto", "ellos"): (("aran", "asen"), ("ieran", "iesen"), ("ieran", "iesen")),
    ("subjuntivo_imperfecto", "nos"): (("áramos", "ásemos"), ("iéramos", "iésemos"), ("iéramos", "iésemos")),
    ("subjuntivo_imperfecto", "tu"): (("aras", "ases"), ("ieras", "ieses"), ("ieras", "ieses")),
    ("subjuntivo_imperfecto", "vos"): (("arais", "aseis"), ("ierais", "ieseis"), ("ierais", "ieseis")),
    ("subjuntivo_imperfecto", "yo"): (("ara", "ase"), ("iera", "iese"), ("iera", "iese")),
    ("subjuntivo_presente", "el"): (("e",), ("a",), ("a",)),
    ("subjuntivo_presente", "ellos"): (("en",), ("an",), ("an",)),
    ("subjuntivo_presente", "nos"): (("emos",), ("amos",), ("amos",)),
    ("subjuntivo_presente", "tu"): (("es",), ("as",), ("as",)),
    ("subjuntivo_presente", "vos"): (("éis",), ("áis",), ("áis",)),
    ("subjuntivo_presente", "yo"): (("e",), ("a",), ("a",)),
}

# Respellings that keep an -ar stem's final consonant sounding the same when the
# ending starts with a front vowel. Tried in order, first match wins, so "gu" is
# listed before "g".
_AR_RESPELL = (
    ("gu", "gü"),   # averiguar -> averigüé
    ("c", "qu"),    # buscar -> busqué
    ("g", "gu"),    # llegar -> llegué
    ("z", "c"),     # cruzar -> crucé
)

# The same for an -er/-ir stem before a back vowel. "gu" and "qu" precede the
# bare letters they contain.
_ER_IR_RESPELL = (
    ("gu", "g"),    # distinguir -> distingo
    ("qu", "c"),    # delinquir -> delinco
    ("c", "z"),     # vencer -> venzo
    ("g", "j"),     # coger -> cojo
)

# Accented vowels count: an -ar verb's preterite "yo" ending is "é", and
# "buscé" would be as wrong as "busce".
_FRONT_VOWELS = frozenset("eiéí")
_BACK_VOWELS = frozenset("aoáó")


def _respell(pattern: str) -> tuple[tuple[tuple[str, str], ...], frozenset[str]]:
    """The respelling table and triggering vowels for a pattern."""
    if pattern == "ar":
        return _AR_RESPELL, _FRONT_VOWELS
    return _ER_IR_RESPELL, _BACK_VOWELS


def _infinitive_ending(infinitive: str) -> str | None:
    """``ar``/``er``/``ir``, or ``None`` outside the three conjugations."""
    for ending in PATTERNS:
        if infinitive.endswith(ending) and len(infinitive) > len(ending):
            return ending
    return None


def patterns_for(infinitive: str) -> list[str]:
    """Which regular patterns this infinitive could follow — at most one.

    Spanish gives no ``-ire``-style ambiguity: the ending names the conjugation.
    The list is kept for the same shape as the other languages' checks.
    """
    ending = _infinitive_ending(infinitive)
    return [ending] if ending else []


def _join(stem: str, ending: str, pattern: str) -> str:
    """Stem + ending, respelling the stem where the ending's vowel demands it."""
    table, vowels = _respell(pattern)
    if not ending or ending[0] not in vowels:
        return stem + ending
    for old, new in table:
        if stem.endswith(old):
            return stem[: len(stem) - len(old)] + new + ending
    return stem + ending


def regular_forms(
    infinitive: str, pattern: str
) -> dict[tuple[str, str], tuple[str, ...]] | None:
    """Every simple-tense cell a verb of this shape would have under ``pattern``.

    Each cell maps to *all* the forms the pattern accepts there, which is more
    than one for the imperfect subjunctive: ``hablara`` and ``hablase`` are both
    regular, and treating either as an irregularity would call every Spanish
    verb irregular.

    ``None`` if the infinitive is outside the three conjugations, or the pattern
    does not apply to it.
    """
    if pattern not in patterns_for(infinitive):
        return None
    index = PATTERNS.index(pattern)
    stem = infinitive[:-2]
    return {
        key: tuple(_join(stem, ending, pattern) for ending in endings[index])
        for key, endings in ENDINGS.items()
    }


# Cells to quote a spelling change from, most recognisable first.
_EXAMPLE_CELLS = (
    ("preterito", "yo"),
    ("presente", "yo"),
    ("subjuntivo_presente", "yo"),
)


@dataclass(frozen=True)
class Spelling:
    """A stem respelling that runs through a whole paradigm predictably."""

    old: str
    new: str
    before: str  # the vowels that trigger it, e.g. "e/é"
    examples: tuple[str, ...]

    def describe(self) -> str:
        return f"{self.old} → {self.new} before {self.before} ({', '.join(self.examples)})"


def spelling_change(infinitive: str) -> Spelling | None:
    """The one respelling this verb's stem needs, if any."""
    patterns = patterns_for(infinitive)
    if not patterns:
        return None
    pattern = patterns[0]
    index = PATTERNS.index(pattern)
    stem = infinitive[:-2]
    table, vowels = _respell(pattern)

    change = next(((o, n) for o, n in table if stem.endswith(o)), None)
    if change is None:
        return None

    triggering = sorted(
        {
            ending[0]
            for e in ENDINGS.values()
            for ending in e[index]
            if ending and ending[0] in vowels
        }
    )
    # Deduplicated: several cells share an ending, so quoting them all would
    # print "busque, busque" instead of "busqué, busque".
    examples: list[str] = []
    for key in _EXAMPLE_CELLS:
        if key not in ENDINGS:
            continue
        ending = ENDINGS[key][index][0]
        form = _join(stem, ending, pattern)
        if form != stem + ending and form not in examples:
            examples.append(form)
    return Spelling(*change, before="/".join(triggering), examples=tuple(examples[:2]))


@dataclass(frozen=True)
class Classification:
    kind: str
    pattern: str | None = None
    spelling: Spelling | None = None

    @property
    def is_regular(self) -> bool:
        return self.kind != IRREGULAR

    def describe(self) -> str:
        """The verdict as a clause to follow the infinitive."""
        if self.kind == IRREGULAR:
            return "is an irregular verb."
        named = PATTERN_NAMES.get(self.pattern, self.pattern)
        if self.kind == REGULAR:
            return f"is a regular {named} verb."
        return (
            f"is a regular {named} verb, apart from a spelling change: "
            f"{self.spelling.describe()}."
        )


def classify(paradigm: Paradigm) -> Classification:
    """Predictable, predictable-but-respelt, or worth drilling.

    Deliberately strict: the cells the table covers must match one pattern
    exactly, so a verb carrying an extra accepted form anywhere is irregular.
    That form is the whole reason to drill it.

    The compound tenses take no part. They are *haber* plus the participle, and
    the participle row is already being checked, so a paradigm that satisfies
    the table has regular compounds by construction.
    """
    for pattern in patterns_for(paradigm.infinitive):
        expected = regular_forms(paradigm.infinitive, pattern)
        if expected is None:
            continue
        covered = {key: cell for key, cell in paradigm.cells.items() if key in expected}
        if set(covered) != set(expected):
            continue
        # Compared as sets: which of several equally regular forms the source
        # happens to list first is not a signal about the verb.
        if not all(set(cell.forms) == set(expected[key]) for key, cell in covered.items()):
            continue
        change = spelling_change(paradigm.infinitive)
        return (
            Classification(REGULAR_WITH_SPELLING, pattern, change)
            if change
            else Classification(REGULAR, pattern)
        )
    return Classification(IRREGULAR)


def is_regular(paradigm: Paradigm) -> bool:
    """True when the paradigm holds nothing the ending table doesn't predict."""
    return classify(paradigm).is_regular
